package com.codedigest.ix.domain

import com.codedigest.ix.data.OutputFormat

object OutputFormatter {

    fun formatTree(treeContent: String, format: OutputFormat): String {
        return when (format) {
            OutputFormat.MARKDOWN -> "# Project Structure\n```text\n$treeContent\n```\n\n"
            OutputFormat.XML -> "<structure>\n$treeContent\n</structure>\n\n"
            OutputFormat.PLAIN_TEXT -> "$treeContent\n\n"
        }
    }

    fun formatFile(name: String, content: String, format: OutputFormat): String {
        val sb = StringBuilder()
        when (format) {
            OutputFormat.XML -> {
                sb.append("<file path=\"$name\">\n")
                sb.append(content)
                sb.append("\n</file>\n\n")
            }
            OutputFormat.MARKDOWN -> {
                val ext = name.substringAfterLast('.', "txt")
                sb.append("## $name\n")
                sb.append("```$ext\n")
                sb.append(content)
                sb.append("\n```\n\n")
            }
            OutputFormat.PLAIN_TEXT -> {
                sb.appendLine("================================================")
                sb.appendLine("FILE: $name")
                sb.appendLine("================================================")
                sb.appendLine(content)
                sb.appendLine()
            }
        }
        return sb.toString()
    }
    
    fun formatHeader(projectName: String, fileCount: Int, tokenCount: Long, format: OutputFormat): String {
        val sb = StringBuilder()
        if (format == OutputFormat.XML) sb.append("<digest_report>\n")
        sb.append("Project: $projectName\n")
        sb.append("Files: $fileCount\n")
        if (tokenCount > 0) sb.append("Tokens: $tokenCount\n")
        sb.append("Generated by CodeDigest\n")
        sb.append("------------------------------------------------\n\n")
        if (format == OutputFormat.XML) sb.append("</digest_report>\n\n")
        return sb.toString()
    }
}
