package com.codedigest.ix

import android.app.Application
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import java.io.File

class CodeDigestApp : Application() {

    override fun onCreate() {
        super.onCreate()
        cleanCache()
    }

    private fun cleanCache() {
        CoroutineScope(Dispatchers.IO).launch {
            try {
                // Clean internal cache files generated by DigestEngine
                val cacheDir = cacheDir
                cacheDir.listFiles()?.forEach { file ->
                    if (file.name.startsWith("digest_body_") && file.name.endsWith(".bin")) {
                        file.delete()
                    }
                }
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
    }
}